:site-url: https://palo-it.github.io/TrainingManager

= TrainingManager
:source-highlighter: rouge

== Technologie

* L'application est contruite avec https://spring.io/projects/spring-boot[Spring Boot].
* Le front est contruit par le moteur de templating https://www.thymeleaf.org/[Tymeleaf].
* Les tests d'interface sont fait via https://playwright.dev/java/[playwright].
* L'intégration continue passe par des https://docs.github.com/fr/actions[Github actions].
* La mise en page et le style utilise https://purecss.io/[Pure CSS].
* La documentation est écrite en https://asciidoctor.org/[asciidoc] et publiée sur une https://docs.github.com/pages[Github pages].

== Interface

Vous pouvez consulter les principaux link:{site-url}/ihm/index.html[parcours utilisateur] de l'application.

== Lancement

Pour lancer l'application, utilisé la commande:
[source,bash]
----
./gradlew bootRun
----

Des tâches gradle ont été ajoutés pour utiliser une configuration spécifique.
L'utilisation de la commande `bootRun[ENV]` va utiliser le fichier `application-[ENV].properties`.
La liste des environnement
Par exemple, pour lancer
[source,bash]
----
./gradlew bootRunDev
----

A noter que le fichier `application-dev.properties` est exclu de Git.
On peut ainsi y mettre sa configuration personnel de développement.

.Plus d'infos
[%collapsible]
====
Les tâches `bootRun[ENV]` font l'équivalent de la commande
[source,bash]
----
./gradlew bootRun --args='--spring.profiles.active=ci'
----

Seuls les environnements définis peuvent être accessible.
La liste de ces environnements est visible avec la commande `./gradlew -q configs`

On peut également choisir le fichier `properties` à utiliser avec la commande:
[source,bash]
----
./gradlew bootRun --args='--spring.config.location=classpath:/application-ci.properties'
----
====

== Configuration

=== Visualisation des requêtes SQL

Pour visualiser les requêtes SQL qui sont exécutés:

[source,properties]
----
# Affichage des requêtes
spring.jpa.show-sql=true
# Mise en forme des requêtes
spring.jpa.properties.hibernate.format_sql=true
----

=== Initialisation des données

Pour initialiser les données de référence dans le base, on passe par le fichier `data.sql` qui est exécuté au lancement.
L'option `spring.jpa.defer-datasource-initialization` pour n'exécuter ce script qu'après la création de la base de données lorsque celle ci est créé au démarrage de l'application.

[source,properties]
----
spring.jpa.defer-datasource-initialization=true
----

Les commandes gradle `bootRun[ENV]` positionne l'attribut `spring.sql.init.platform` avec le nom de l'environnement indiqué.
Ainsi la commande `bootRundev` va exécuter le script `data.sql` et `data-dev.sql`.

=== Configuration des services

Il est possible de choisir le service d'émargement utilisé en fonction de l'environnement.
Cela est fait à partir du profil utilisé et positionné sur la variable `spring.profiles.active`.

Une classe service peut indiquer avec quels type de profile elle sera utilisé.
Cela se fait en ajoutant l'annotation `@Profile`.

On utilisera le profile `prod` pour la production.

Example d'un service injecté pour les profiles "dev" et "ci":
[source, java]
----
@Service
@Profile({"!prod"})
public class DocusignMockService implements EmargementService {
    // Mon code
}
----

=== DocuSign

Une link:{site-url}/docusign.html[page dédiée à DocuSign] décrit la manière de la configurer.

== Intégration continue

L'intégration continue est géré via des Github Actions.
La configuration se trouve dans le répértoire `.github/workflows`

== Docker

Si vous souhaitez démarrer l'application et les tests sous docker, vous trouverez des indications sur cette page: link:{site-url}/docker.html[Docker]