= TrainingManager
:source-highlighter: rouge

== Technologie

* L'application est contruite avec https://spring.io/projects/spring-boot[Spring Boot].
* Le front est contruit par le moteur de templating https://www.thymeleaf.org/[Tymeleaf].
* Les tests d'interface sont fait via https://playwright.dev/java/[playwright].
* L'intégration continue passe par des https://docs.github.com/fr/actions[Github actions].
* La mise en page et le style utilise https://purecss.io/[Pure CSS].
* La documentation est écrite en https://asciidoctor.org/[asciidoc] et publiée sur une https://docs.github.com/pages[Github pages].


== Lancement

Pour lancer l'application, utilisé la commande:
[source,bash]
----
./gradlew bootRun
----

Des tâches gradle ont été ajoutés pour utiliser une configuration spécifique.
L'utilisation de la commande `bootRun[ENV]` va utiliser le fichier `application-[ENV].properties`.
La liste des environnement
Par exemple, pour lancer
[source,bash]
----
./gradlew bootRunDev
----

A noter que le fichier `application-dev.properties` est exclu de Git.
On peut ainsi y mettre sa configuration personnel de développement.

.Plus d'infos
[%collapsible]
====
Les tâches `bootRun[ENV]` font l'équivalent de la commande
[source,bash]
----
./gradlew bootRun --args='--spring.profiles.active=ci'
----

Seuls les environnements définis peuvent être accessible.
La liste de ces environnements est visible avec la commande `./gradlew -q configs`

On peut également choisir le fichier `properties` à utiliser avec la commande:
[source,bash]
----
./gradlew bootRun --args='--spring.config.location=classpath:/application-ci.properties'
----
====

== Configuration

Pour visualiser les requêtes SQL qui sont exécutés:

[source,properties]
----
# Affichage des requêtes
spring.jpa.show-sql=true
# Mise en forme des requêtes
spring.jpa.properties.hibernate.format_sql=true
----

== Intégration continue

L'intégration continue est géré via des Github Actions.
La configuration se trouve dans le répértoire `.github/workflows`

== Docker

=== Prerequis

Pour executer gradlew dans docker, il a besoin d'être executable.
[source,bash]
----
chmod ug+x gradlew
----

=== Execution

Pour démarrer un environnement complet (mysql + springboot):
[source,bash]
----
docker-compose up
----

Le schéma de base de données est recréé au démarrage.

Les variables d'environnement utilisées se trouve dans le fichier `.env` à la racine du projet.

* Application formation: http://localhost:6868/formations
* PhpAdmin: http://localhost:8090/

Pour démarre SpringBoot seul en ligne de commande:
[source,bash]
----
docker run -v $(pwd):/project -w /project -p 8080:8080 -it gradle:8.3.0-jdk17-alpine /bin/bash
./gradlew bootRun
----

Le script `run_tests.sh` permet de démarrer l'environnement et d'exécuter les tests.

Pour lancer directement les tests, on peut démarrer le docker-compose avec le profil "test"
[source,bash]
----
docker compose --profile test up -d
----

Pour uniquement lancer l'application avec la base de données:
[source,bash]
----
docker compose up -d
----

Vous pouvez ensuite executer les tests depuis l'environnement local avec
[source,bash]
----
npx playwright test
----
ou
[source,bash]
----
npx playwright test --ui
----
