= TrainingManager

== Technologie

L'application est contruite avec https://spring.io/projects/spring-boot[Spring Boot]. +
Le front est contruit par le moteur de templating https://www.thymeleaf.org/[Tymeleaf]. +
Les tests d'interface sont fait via https://playwright.dev/java/[playwright]. +
L'intégration continue passe par des https://docs.github.com/fr/actions[Github actions].

== Intégration continue

L'intégration continue est géré via des Github Actions.
La configuration se trouve dans le répértoire `.github/workflows`

== Docker

=== Prerequis

Pour executer gradlew dans docker, il a besoin d'être executable.
----
chmod ug+x gradlew
----

=== Execution

Pour démarrer un environnement complet (mysql + springboot):
----
docker-compose up
----

Le schéma de base de données est recréé au démarrage.

Les variables d'environnement utilisées se trouve dans le fichier `.env` à la racine du projet.

* Application formation: http://localhost:6868/formations
* PhpAdmin: http://localhost:8090/

Pour démarre SpringBoot seul en ligne de commande:
----
docker run -v $(pwd):/project -w /project -p 8080:8080 -it gradle:8.3.0-jdk17-alpine /bin/bash
./gradlew bootRun
----

Le script `run_tests.sh` permet de démarrer l'environnement et d'exécuter les tests.

Pour lancer directement les tests, on peut démarrer le docker-compose avec le profil "test"
----
docker compose --profile test up -d
----

Pour uniquement lancer l'application avec la base de données:
----
docker compose up -d
----

Vous pouvez ensuite executer les tests depuis l'environnement local avec
----
npx playwright test
----
ou
----
npx playwright test --ui
----