= DocuSign
:toc: left

`https://www.docusign.com[DocuSign]` est l'application utilisée pour envoyer les feuilles d'émargement.


== Configuration DocuSign

L'https://apps.docusign.com[application DocuSign] permet de gérer les modèles, suivre les envois.

Il est nécessaire d'avoir un compte pour l'utilisation de l'API.
Le site pour le développement d'API est https://developers.docusign.com/.
On peut y trouver le `User Id` et l'`Account ID`

On peut accéder à l'https://appdemo.docusign.com[interface d'administration de développement] pour voir les mails envoyés.

== Configuration de l'application

Le fichier `docusign.properties` se trouve dans le répertoire `resources`  de l'application.

Il contient les clés suivantes:

* docusign.clientId=[Identifiant client]
* docusign.userId=[Identifiant utilisateur]
* docusign.rsaKeyFile=[chemin vers la clé privée]

Il faut faire pointer le chemin rsaKeyFile vers le fichier contenant la clé privée.

== Environnement de développement

Un bouchon est mis en place pour DocuSign afin ne pas intéragir avec le vrai service en dehors de la production.
Pour utiliser le vrai service `DocuSign` (en production), il faut positionner le profile spring à `docusign`.

== Positionnement des tabs

Lorsque rien n'est précisé, l'utilisateur pour positionner différents champs dans son document (signature, nom, date, ...).

En positionnant le tabs, la signature est imposé et ne peut pas être déplacée.

Explications sur le positionnement des tabs:

* https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/tabs/fixed/
* https://www.docusign.com/blog/developers/tabs-deep-dive-placing-tabs-documents

On peut utiliser le setAnchorString pour placer la signature à côté d'un texte.
Il y aura une signature demandé à chaque endroit où apparait le texte.

== Utilisation dans l'application

On va envoyer une feuille d'émargement à l'ensemble des particpants plutôt qu'une feuille d'émargement par personne.
Cela permet de centraliser les signatures au niveau de l'administration DocuSign.

Lorsqu'un utilisateur accède au docuement pour le signer, il se connecte au serveur et voit les signatures déjà apposées sur celui çi.