name: Contruction du projet

on:
  push:

jobs:
    contruire-projet:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Préparation Gradle
        uses: gradle/gradle-build-action@v2
      - name: Construction du projet
        run: ./gradlew build