name: Contruction du projet

on:
  push:
    branches: ['master']

jobs:
  contruire-projet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Préparation Gradle
      uses: gradle/gradle-build-action@v2
    - name: Construction du projet
      run: ./gradlew build

  test-playwright:
    uses: ./.github/workflows/playwright-test.yml

  publication-doc:
    needs: test-playwright
    uses: ./.github/workflows/publish-doc.yml