# Action to transform asciidoc files in HTML and publish the result to a specific branch.

name: GitHub Pages Publish

on:
  workflow_call:

env:
  doc_branch: 'gh_pages'
  working_branch: 'tmp_branch_for_doc'
  user_manual_branch: 'tmp_user_manuel'
  published_folder: 'generated_docs'
  adoc_folder: 'docs'

jobs:

  publish-doc:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
    steps:
      - uses: actions/checkout@v4
      - name: Configuration Git
        run: |
          git config --global --add safe.directory $(realpath .)
          git config user.email github-action@github.com
          git config user.name github-action

      - name: Récupération de la branche de travail
        run: |
          git checkout -b ${{env.working_branch}}

      - name: Generation du HTML
        run: |
          git fetch origin ${{env.user_manual_branch}}
          git checkout origin/${{env.user_manual_branch}}  -- ${{env.adoc_folder}}/ihm
          asciidoctor -r asciidoctor-diagram -D ${{env.published_folder}} -R ${{env.adoc_folder}} $(find ${{env.adoc_folder}} -type f -name "[^_]*.adoc")
          rm -rf ${{env.published_folder}}/.asciidoctor

      - name: Copie des fichiers autres que asciidoc
        run: |
          cd ${{env.adoc_folder}}
          find . -not -name '*.adoc' -exec cp --parents {} ../${{env.published_folder}}/ \;

      - name: Ajout des documents dans la branche de travail
        run: |
          echo "Ajout du répertoire de documentation"
          git add ${{env.published_folder}}
          git commit -m "Mise à jour de la documentation"

          echo "Récupération de la branche de documentation"
          git fetch origin ${{env.doc_branch}}
          git checkout ${{env.doc_branch}}

          echo "Remplacement des documents par la nouvelle version"
          git rm -rf .
          git checkout ${{env.working_branch}}  -- ${{env.published_folder}}
          git mv ${{env.published_folder}}/* .

          echo "Commit et push des modification"
          git commit -m "Mise à jour de la documentation"
          git push -f

# Need to set pages to publish in Github settings
# Settings > Pages > GitHub Pages > Build and deployment
# Source: Deploy from a branch
# Branch: Select the branch with doc
# Folder: / (root)